env:
  es2017: true
  node: true

extends: eslint:recommended

ignorePatterns: "/example/demo"

parserOptions:
  ecmaVersion: 9

rules:
  arrow-parens: [2, "as-needed"]
  camelcase: 1
  comma-style: [1, "last"]
  curly: [2, "all"]
  default-case: 2
  dot-notation: 1
  eol-last: 1
  eqeqeq: [2, "allow-null"]
  guard-for-in: 2
  key-spacing: [1, { beforeColon: false, afterColon: true, mode: "minimum" }]
  max-len: [1, 98, 4, { "ignoreComments": true }]
  new-cap: 2
  no-caller: 1
  no-floating-decimal: 2
  no-multi-str: 1
  no-nested-ternary: 2
  no-new: 2
  no-trailing-spaces: 1
  no-var: 2
  object-curly-spacing: [1, "always"]
  one-var: [1, "never"]
  operator-linebreak: [1, "before", { overrides: { "?": "after", ":": "after" } }]
  prefer-const: 2
  radix: 2
  semi-spacing: 1
  semi-style: 2
  space-before-blocks: 1
  space-in-parens: [1, "never"]
  space-unary-ops: 1
  spaced-comment: [2, "always", { exceptions: ["-"] }]
  strict: [2, "global"]
  valid-jsdoc: [1, { requireReturn: false, prefer: { return: "returns" }}]
  wrap-iife: 2

overrides:

  - files: ["*.js"]

    rules:
      brace-style: [2, "1tbs"]
      comma-dangle: [1, "never"]
      comma-spacing: 2
      indent: [1, 'tab']
      keyword-spacing: 2
      no-shadow: 1
      no-use-before-define: 2
      prefer-rest-params: 2
      prefer-spread: 2
      quotes: [1, "single", "avoid-escape"]
      semi: 2
      space-before-function-paren: [1, { "named": "never" }]
      space-infix-ops: 1

  - files: ["*.ts"]

    extends: [plugin:@typescript-eslint/recommended]

    rules:
      "@typescript-eslint/brace-style": [2, "1tbs"]
      "@typescript-eslint/comma-dangle": [1, "never"]
      "@typescript-eslint/comma-spacing": 2
      "@typescript-eslint/indent": [1, 'tab']
      "@typescript-eslint/keyword-spacing": 2
      "@typescript-eslint/member-delimiter-style": 2
      "@typescript-eslint/no-shadow": 1
      "@typescript-eslint/no-use-before-define": 2
      "@typescript-eslint/quotes": [1, "single", "avoid-escape"]
      "@typescript-eslint/semi": 2
      "@typescript-eslint/space-before-function-paren": [1, { "named": "never" }]
      "@typescript-eslint/space-infix-ops": 1
