parserOptions:
  ecmaVersion: 9

extends: eslint:recommended

env:
  node: true

rules:
  brace-style: [2, "1tbs"]
  camelcase: 1
  comma-dangle: [1, "never"]
  comma-spacing: 2
  comma-style: [1, "last"]
  curly: [2, "all"]
  default-case: 2
  dot-notation: 1
  eol-last: 1
  eqeqeq: [2, "allow-null"]
  func-style: [2, "declaration"]
  guard-for-in: 2
  indent: [1, 'tab']
  key-spacing: [1, { beforeColon: false, afterColon: true, mode: "minimum" }]
  keyword-spacing: [2, { after: true }]
  max-len: [1, 98, 4, { "ignoreComments": true }]
  new-cap: 2
  no-alert: 2
  no-caller: 1
  no-floating-decimal: 2
  no-multi-str: 1
  no-nested-ternary: 2
  no-new: 2
  no-shadow: 1
  no-trailing-spaces: 1
  no-use-before-define: 2
  no-var: 2
  object-curly-spacing: [1, "always"]
  operator-linebreak: [1, "before", { overrides: { "?": "after", ":": "after" } }]
  prefer-const: 2
  quotes: [1, "single", "avoid-escape"]
  radix: 2
  semi: 2
  semi-spacing: 1
  semi-style: 2
  space-before-blocks: 1
  space-before-function-paren: [1, { "named": "never" }]
  space-in-parens: [1, "never"]
  space-infix-ops: 1
  space-unary-ops: 1
  spaced-comment: [2, "always", { exceptions: ["-"] }]
  strict: [2, "global"]
  valid-jsdoc: [1, { requireReturn: false, prefer: { return: "returns" }}]
  wrap-iife: 2
