env:
  es2020: true
  node: true

extends:
  - eslint:recommended
  - plugin:eslint-comments/recommended

ignorePatterns:
  - /coverage
  - /example/demo

reportUnusedDisableDirectives: true

rules:
  arrow-parens: [2, "as-needed"]
  camelcase: 1
  comma-style: [2, "last"]
  curly: [2, "all"]
  default-case: 1
  dot-notation: 1
  eol-last: 2
  eqeqeq: [2, "allow-null"]
  func-names: [1, "never"]
  guard-for-in: 1
  key-spacing: [2, { beforeColon: false, afterColon: true, mode: "minimum" }]
  max-len: [1, 100, 4]
  new-cap: [2, { capIsNewExceptions: ['TypeError'] }]
  no-floating-decimal: 2
  no-multi-str: 1
  no-multiple-empty-lines: 2
  no-nested-ternary: 2
  no-new: 2
  no-trailing-spaces: 1
  no-var: 2
  one-var: [1, "never"]
  operator-linebreak: [2, "before", { overrides: { "?": "after", ":": "after" } }]
  prefer-arrow-callback: 1
  prefer-const: 2
  semi-spacing: 2
  semi-style: 2
  space-before-blocks: 2
  space-in-parens: [2, "never"]
  space-unary-ops: 2
  spaced-comment: [2, "always", { exceptions: ["-"] }]
  strict: [2, "global"]
  valid-jsdoc: [1, { requireReturn: false, prefer: { return: "returns" }}]

overrides:

  - files: ["*.js"]

    rules:
      brace-style: [2, "1tbs"]
      comma-dangle: 1
      comma-spacing: 2
      indent: [1, "tab"]
      keyword-spacing: 2
      no-shadow: 1
      no-use-before-define: 2
      object-curly-spacing: [2, "always"]
      prefer-rest-params: 2
      prefer-spread: 2
      quotes: [1, "single", "avoid-escape"]
      semi: 2
      space-before-function-paren: [1, { "named": "never" }]
      space-infix-ops: 1

  - files: ["*.ts"]

    extends: plugin:@typescript-eslint/recommended

    rules:
      "@typescript-eslint/brace-style": [2, "1tbs"]
      "@typescript-eslint/comma-dangle": 1
      "@typescript-eslint/comma-spacing": 2
      "@typescript-eslint/indent": [1, "tab"]
      "@typescript-eslint/keyword-spacing": 2
      "@typescript-eslint/member-delimiter-style": 2
      "@typescript-eslint/no-shadow": 1
      "@typescript-eslint/no-use-before-define": 2
      "@typescript-eslint/object-curly-spacing": [2, "always"]
      "@typescript-eslint/quotes": [1, "single", "avoid-escape"]
      "@typescript-eslint/semi": 2
      "@typescript-eslint/space-before-function-paren": [1, { "named": "never" }]
      "@typescript-eslint/space-infix-ops": 1
