name: Node.js CI

on: [push, pull_request]

jobs:

  lint:

    name: lint & ts-test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: |
        npm install
        npm run lint
        npm run ts-test

  test:

    name: test (Node.js ${{ matrix.node-version }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['12', '14', '16', '18']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm test
